# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"

In [3]:
s.split(" ")

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742

In [5]:
"The diameter of {0} is {1} kilometers.".format(planet,diameter)

'The diameter of Earth is 12742 kilometers.'

## 3. In this nest dictionary grab the word "hello"

In [6]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [7]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [8]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [11]:
np.arange(start=20,stop=35,step=2)

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [13]:
np.concatenate((np.array([1,2,3]),np.array([4,5,6])),axis=None)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [14]:
import pandas as pd


In [15]:
pd.DataFrame([[0,1],[0,1],[0,1]],columns=['Zeros','Ones'])

Zeros  Ones
0      0     1
1      0     1
2      0     1

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [22]:
pd.Series(pd.date_range(start='1-1-2033',periods=41,freq='D'))

0    2033-01-01
1    2033-01-02
2    2033-01-03
3    2033-01-04
4    2033-01-05
5    2033-01-06
6    2033-01-07
7    2033-01-08
8    2033-01-09
9    2033-01-10
10   2033-01-11
11   2033-01-12
12   2033-01-13
13   2033-01-14
14   2033-01-15
15   2033-01-16
16   2033-01-17
17   2033-01-18
18   2033-01-19
19   2033-01-20
20   2033-01-21
21   2033-01-22
22   2033-01-23
23   2033-01-24
24   2033-01-25
25   2033-01-26
26   2033-01-27
27   2033-01-28
28   2033-01-29
29   2033-01-30
30   2033-01-31
31   2033-02-01
32   2033-02-02
33   2033-02-03
34   2033-02-04
35   2033-02-05
36   2033-02-06
37   2033-02-07
38   2033-02-08
39   2033-02-09
40   2033-02-10
dtype: datetime64[ns]

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [23]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [25]:
pd.DataFrame(lists, columns=['S.No.','Name','Average'])

S.No. Name  Average
0      1  aaa       22
1      2  bbb       25
2      3  ccc       24